

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=rejestr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rejestr12345
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code/
    ports:
      - "8001:8001"
    depends_on:
      - db
