# Generated by Django 4.1.3 on 2022-11-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kadry_k',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_umowy', models.CharField(max_length=30)),
                ('data_pod', models.DateField()),
                ('personel', models.CharField(choices=[('L', 'LEKARZ'), ('P', 'PIELĘGNIARKA'), ('F', 'FIZJOTERAPEUTA')], default='L', max_length=1)),
                ('kontrahent', models.CharField(max_length=255)),
                ('przedmiot', models.CharField(max_length=255)),
                ('od', models.DateField()),
                ('do', models.DateField()),
                ('attachments', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Kadry_z',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_umowy', models.CharField(max_length=30)),
                ('data_pod', models.DateField()),
                ('personel', models.CharField(choices=[('L', 'LEKARZ'), ('P', 'PIELĘGNIARKA'), ('F', 'FIZJOTERAPEUTA')], default='L', max_length=1)),
                ('kontrahent', models.CharField(max_length=255)),
                ('przedmiot', models.CharField(max_length=255)),
                ('od', models.DateField()),
                ('do', models.DateField()),
                ('attachments', models.FileField(upload_to='')),
            ],
        ),
    ]
