# Generated by Django 4.1.3 on 2022-11-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0002_alter_kadry_k_attachments_alter_kadry_z_attachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kadry_k',
            old_name='data_pod',
            new_name='data_podpisania',
        ),
        migrations.RenameField(
            model_name='kadry_z',
            old_name='data_pod',
            new_name='data_podpisania',
        ),
    ]
