# Generated by Django 4.1.3 on 2022-12-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0003_rename_data_pod_kadry_k_data_podpisania_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kadry_k',
            options={'verbose_name': 'Kadry-kontrakty'},
        ),
        migrations.AddField(
            model_name='kadry_k',
            name='typ_umowy',
            field=models.CharField(choices=[('K', 'KONTRAKT'), ('Z', 'ZLECENIE')], default='K', max_length=1),
        ),
    ]
