# Generated by Django 4.1.3 on 2022-12-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0004_alter_kadry_k_options_kadry_k_typ_umowy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kadry_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_aneksu', models.CharField(max_length=30)),
                ('data_podpisania', models.DateField()),
                ('od', models.DateField()),
                ('do', models.DateField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('kadry_k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestr.kadry_k')),
            ],
            options={
                'verbose_name': 'Kadry-aneksy',
            },
        ),
    ]
