# Generated by Django 4.1.3 on 2022-12-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0006_kadry_k_nr_postepowania'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kadry_a',
            old_name='kadry_k',
            new_name='nr_umowy',
        ),
    ]
