# Generated by Django 4.1.3 on 2022-12-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0007_rename_kadry_k_kadry_a_nr_umowy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kadry_a',
            old_name='attachments',
            new_name='załącznik',
        ),
        migrations.RenameField(
            model_name='kadry_k',
            old_name='attachments',
            new_name='załącznik',
        ),
        migrations.RenameField(
            model_name='kadry_z',
            old_name='attachments',
            new_name='załącznik',
        ),
    ]
