# Generated by Django 4.1.3 on 2022-12-02 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rejestr', '0008_rename_attachments_kadry_a_załącznik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kadry_k',
            name='dodal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
