# Generated by Django 4.1.3 on 2022-12-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0018_sprzedaz_sprzedaz_a_delete_kadry_z_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_umowy', models.CharField(max_length=30)),
                ('data_podpisania', models.DateField()),
                ('nr_postepowania', models.CharField(blank=True, max_length=30, null=True)),
                ('kontrahent', models.CharField(max_length=255)),
                ('przedmiot', models.CharField(max_length=255)),
                ('od', models.DateField()),
                ('do', models.DateField()),
                ('załącznik', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Zamówienia Publiczne',
            },
        ),
        migrations.CreateModel(
            name='Zamowienia_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_aneksu', models.CharField(max_length=30)),
                ('data_podpisania', models.DateField()),
                ('od', models.DateField()),
                ('do', models.DateField()),
                ('załącznik', models.FileField(blank=True, null=True, upload_to='')),
                ('nr_umowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestr.zamowienia')),
            ],
            options={
                'verbose_name_plural': 'Zamówienia-aneksy',
            },
        ),
    ]
