# Generated by Django 4.1.3 on 2022-12-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0020_pozostale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapytania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_umowy', models.CharField(max_length=30)),
                ('data_podpisania', models.DateField()),
                ('nr_postepowania', models.CharField(blank=True, max_length=30, null=True)),
                ('kontrahent', models.CharField(max_length=255)),
                ('przedmiot', models.CharField(max_length=255)),
                ('od', models.DateField()),
                ('do', models.DateField()),
                ('załącznik', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Zapytania ofertowe',
            },
        ),
    ]
