# Generated by Django 4.1.3 on 2023-08-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0022_kadry_k_badania_medyczne_kadry_k_polisa_oc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzedaz',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
